# Generated by Django 6.0 on 2025-12-30 18:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_reciept_remove_person_session_delete_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tax', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('service', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Reciept',
        ),
        migrations.AddField(
            model_name='person',
            name='session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='app.session'),
        ),
    ]
