# Generated by Django 6.0 on 2025-12-30 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_person_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='app.session'),
        ),
    ]
