# Generated by Django 6.0 on 2025-12-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='amount',
        ),
    ]
